palladiumkenya/openmrs-module-kenyaEMRCashier

- api/src/main/java/org/openmrs/module/kenyaemr/cashier/advice/OrderCreationMethodBeforeAdvice.java
Handle billing for procedures and radiology/imaging services
> handle billing for procedures and radiology/imaging services

- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/impl/BillServiceImpl.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/model/Bill.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/search/BillSearch.java
- omod/src/main/java/org/openmrs/module/kenyaemr/cashier/rest/resource/BillResource.java
- omod/src/main/resources/liquibase.xml
https://thepalladiumgroup.atlassian.net/browse/KHP3-5741
> (feat) filter bills by date created

- omod/pom.xml
- omod/src/main/java/org/openmrs/module/kenyaemr/cashier/rest/controller/CashierRestController.java
- omod/src/main/java/org/openmrs/module/kenyaemr/cashier/rest/restmapper/BillableServiceMapper.java
- omod/src/main/java/org/openmrs/module/kenyaemr/cashier/rest/restmapper/CashierItemPriceMapper.java
Endpoint : [/openmrs/ws/rest/v1/cashier/api/billable-service](https://github.com/openmrs/ws/rest/v1/cashier/api/billable-service)
Method : POST
For a new entry save, uuid is not supplied but for updates, the payload has to inlcude uuid key i.e :
> enable update of existing BillableService object

- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/model/BillLineItem.java
- omod/src/main/java/org/openmrs/module/kenyaemr/cashier/rest/resource/BillLineItemResource.java
Add concept reference for stock/billable service in bill line item
> Add concept reference for bill line item

- api/src/main/java/org/openmrs/module/kenyaemr/cashier/advice/GenerateBillFromOrderable.java
This PR changes the source of stock item price to use the stock item details. It ignores any prices set in the billable services module for the item
> Get the correct stock item price from stock details

- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/model/BillStatus.java
This PR adds CREDITED bill status to take care of refunds.
> Add credited bill status

- omod/src/main/resources/config.xml
Reverts palladiumkenya/openmrs-module-kenyaEMRCashier#35
> Revert "configure module not to require jasper reports module"

- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/model/BillLineItem.java
- omod/src/main/java/org/openmrs/module/kenyaemr/cashier/rest/resource/BillLineItemResource.java
This should enable filtering or billing history by serviceTypes
> add serviceTypeUuid property for filtering bills

- api/src/main/java/org/openmrs/module/kenyaemr/cashier/advice/GenerateBillFromOrderable.java
Fix association for bill line item and order
> Fix association for bill line item and order

- EXEMPTIONSGUIDE.md
Due to frequent support requests regarding billing exemption implementation and configuration, this PR adds comprehensive documentation to assist teams and reduce repetitive explanations.
Changes:
1. Added step-by-step guide for implementing billing exemptions
2. Included configuration examples and best practices
3. Listed common troubleshooting scenarios and solutions
> (docs) : Add Billing Exemption Implementation Guide

- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/impl/BillServiceImpl.java
Add payment reference code in the receipt
> Add payment reference code to payment details

- api/src/main/java/org/openmrs/module/kenyaemr/cashier/advice/GenerateBillFromOrderable.java
Canceling an order should also cancel the associated bill.
> KHP3-7301: Canceling an order should also cancel the associated bill

- api/pom.xml
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/advice/GenerateBillFromOrderable.java
- omod/src/main/resources/config.xml
- pom.xml
This PR adds:
1. Dependency on orderexpansion module
2. Listens to medicalsupplyorder requests and generate bills
> KHP3-7302: Introduce medical supply orders, and generate bills from orders

- omod/pom.xml
- pom.xml
At the moment we are unable to publish the omod. This is because of naming of artifactId 
Hopefully this fixes this issue 😄
> fix : Adjust artifactId to ensure we have the omod sub-module published

- omod/src/main/java/org/openmrs/module/kenyaemr/cashier/rest/controller/CashierRestController.java
This pull request introduces a new REST API endpoint to delete a billable service by its UUID.
> (feat) : Add delete endpoint for billiabe items

- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/IDepositService.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/IDepositTransactionService.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/impl/DepositEntityDataServiceImpl.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/impl/DepositServiceImpl.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/impl/DepositTransactionEntityDataServiceImpl.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/impl/DepositTransactionServiceImpl.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/model/BillLineItem.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/model/Deposit.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/model/DepositStatus.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/model/DepositTransaction.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/model/TransactionType.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/util/PrivilegeConstants.java
- api/src/main/resources/moduleApplicationContext.xml
- api/src/test/java/org/openmrs/module/kenyaemr/cashier/api/IDepositServiceTest.java
- api/src/test/resources/dataset/DepositTest.xml
- api/src/test/resources/log4j.dtd
- api/src/test/resources/log4j.xml
- docs/deposit.md
- omod/src/main/java/org/openmrs/module/kenyaemr/cashier/rest/resource/BillLineItemResource.java
- omod/src/main/java/org/openmrs/module/kenyaemr/cashier/rest/resource/BillResource.java
- omod/src/main/java/org/openmrs/module/kenyaemr/cashier/rest/resource/DepositResource.java
- omod/src/main/java/org/openmrs/module/kenyaemr/cashier/rest/resource/DepositTransactionResource.java
- omod/src/main/java/org/openmrs/module/kenyaemr/cashier/rest/search/DepositSearchHandler.java
- omod/src/main/resources/hibernate.cfg.xml
- omod/src/main/resources/liquibase.xml
- omod/src/main/resources/org/openmrs/module/kenyaemr/cashier/api/model/Bill.hbm.xml
This PR implements a patient deposit management system to streamline the handling of service deposits in the cashier module. The feature enables healthcare facilities to better manage upfront payments for services that require deposits.
ticket 👉🏽  https://thepalladiumgroup.atlassian.net/browse/KHP3-6991
1. **Deposit Creation**
- Cashier/Finance users can create deposits for specific patients
- Each deposit is linked to particular billable services
- System maintains a clear audit trail of deposit transactions
- Unique reference numbers for easy tracking
2. **Bill Settlement Integration**
- Automatic application of deposits to pending bills
- Real-time balance tracking for each deposit
- Support for partial deposit utilization
- Clear visibility of deposit status (active, used, voided)
3. …
> (feat) KHP3-6991 : Add model to support ability to manage deposit and assign it to bills or line_items

- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/impl/DepositServiceImpl.java
Resolve spring bean creation in `DepositServiceImp`
> (fix) resolve spring bean creation in `DepositServiceImp`

- api/pom.xml
- omod/pom.xml
- pom.xml
> Bumped to v4.2.2

- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/impl/BillServiceImpl.java
Add section to show **Amount Due**, if any deposit has been used to settle the bill then also have it shown on the receipt.
> feat: Add deposit and balance due on the printed receipts

- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/impl/BillServiceImpl.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/impl/DepositServiceImpl.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/model/Bill.java
- omod/src/main/java/org/openmrs/module/kenyaemr/cashier/rest/resource/BillableServiceResource.java
This PR addresses two issues:
1. Bill Status Synchronization Fix
- Resolves synchronization issues with bill status updates after processing
- Ensures bill status is marked correctly throughout the processing workflow
2. Enhanced Billable Services Search
- Adds support for searching billable services using drugUuid parameter
- Enables accurate billing during drug bill generation by improving service lookup functionality
> feat: Add ability to search billable service using drugUuid & resolve issues with syncing bill status

- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/util/CurrencyUtil.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/util/pdfgeneration/billstatement/BillStatementContentSection.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/util/pdfgeneration/billstatement/BillStatementLetterheadSection.java
- api/src/main/java/org/openmrs/module/kenyaemr/cashier/api/util/pdfgeneration/invoice/InvoiceContentSection.java
- api/src/main/resources/messages.properties
- api/src/main/resources/messages_am.properties
- api/src/test/java/org/openmrs/module/kenyaemr/cashier/api/util/CurrencyUtilTest.java
Add support to translate currency within the app, pdf documents
> feat : Add support for internationalization with support for amharic

- api/pom.xml
- omod/pom.xml
- pom.xml
Bumped to version 4.2.3 stable
> Bumped to version 4.2.3 stable
